export interface FmeaRow {
  id: string
  process: string
  mode: string
  effect: string
  sev: number
  cause: string
  pc: string
  occ: number
  dc: string
  det: number
  rpn: number
  ap: string
  action: string
  resp: string
  date: string
  status: "closed" | "pending"
  sev2: number
  occ2: number
  det2: number
  rpn2: number
}

/* ── Helper: Calculate RPN and AP from S/O/D ── */
export function calculateRpn(sev: number, occ: number, det: number): number {
  return sev * occ * det
}

export function calculateAp(rpn: number): string {
  if (rpn >= 100) return "H"
  if (rpn >= 50) return "M"
  return "L"
}

/* ── Helper: Create a new blank FMEA row ── */
export function createBlankRow(process: string = ""): FmeaRow {
  return {
    id: `new-${Date.now()}`,
    process,
    mode: "",
    effect: "",
    sev: 5,
    cause: "",
    pc: "",
    occ: 3,
    dc: "",
    det: 3,
    rpn: 45,
    ap: "L",
    action: "",
    resp: "",
    date: new Date().toISOString().slice(0, 10),
    status: "pending",
    sev2: 5,
    occ2: 2,
    det2: 2,
    rpn2: 20,
  }
}

/* ── Initial FMEA Data ── */
export const initialFmeaData: FmeaRow[] = [
  {
    id: "fmea-001",
    process: "上盖注塑",
    mode: "收缩变形",
    effect: "装配间隙过大",
    sev: 8,
    cause: "保压时间不足",
    pc: "模流分析",
    occ: 4,
    dc: "首件三次元测量",
    det: 3,
    rpn: 96,
    ap: "M",
    action: "增加保压时间2s",
    resp: "工艺工程部",
    date: "2026-05-10",
    status: "closed",
    sev2: 8,
    occ2: 2,
    det2: 3,
    rpn2: 48,
  },
  {
    id: "fmea-002",
    process: "卡扣结构",
    mode: "根部断裂",
    effect: "上下盖脱落",
    sev: 9,
    cause: "R角设计不足",
    pc: "DFM评审",
    occ: 5,
    dc: "拉力测试",
    det: 4,
    rpn: 180,
    ap: "H",
    action: "增大根部R角",
    resp: "结构设计部",
    date: "2026-05-12",
    status: "pending",
    sev2: 9,
    occ2: 2,
    det2: 2,
    rpn2: 36,
  },
  {
    id: "fmea-003",
    process: "密封圈装配",
    mode: "漏装",
    effect: "防水失效IP等级不达标",
    sev: 9,
    cause: "手工作业遗漏",
    pc: "防错夹具",
    occ: 3,
    dc: "气密性测试",
    det: 2,
    rpn: 54,
    ap: "M",
    action: "增加视觉检测工位",
    resp: "品质工程部",
    date: "2026-05-15",
    status: "closed",
    sev2: 9,
    occ2: 1,
    det2: 2,
    rpn2: 18,
  },
  {
    id: "fmea-004",
    process: "SMT贴片",
    mode: "虚焊/偏移",
    effect: "电路板功能异常",
    sev: 7,
    cause: "锡膏印刷参数偏差",
    pc: "SPI检测",
    occ: 3,
    dc: "AOI光学检测",
    det: 2,
    rpn: 42,
    ap: "L",
    action: "优化钢网开口设计",
    resp: "SMT工程部",
    date: "2026-05-18",
    status: "closed",
    sev2: 7,
    occ2: 2,
    det2: 2,
    rpn2: 28,
  },
  {
    id: "fmea-005",
    process: "波峰焊",
    mode: "桥接短路",
    effect: "PCB烧毁",
    sev: 10,
    cause: "助焊剂涂覆不均",
    pc: "波峰焊参数监控",
    occ: 2,
    dc: "ICT在线测试",
    det: 2,
    rpn: 40,
    ap: "L",
    action: "增加助焊剂流量传感器",
    resp: "焊接工程部",
    date: "2026-05-20",
    status: "closed",
    sev2: 10,
    occ2: 1,
    det2: 2,
    rpn2: 20,
  },
  {
    id: "fmea-006",
    process: "功能测试",
    mode: "误判PASS",
    effect: "不良品流出",
    sev: 8,
    cause: "测试程序覆盖率不足",
    pc: "测试用例评审",
    occ: 3,
    dc: "抽检复测",
    det: 5,
    rpn: 120,
    ap: "H",
    action: "补充边界条件测试用例",
    resp: "测试工程部",
    date: "2026-05-22",
    status: "pending",
    sev2: 8,
    occ2: 2,
    det2: 3,
    rpn2: 48,
  },
  {
    id: "fmea-007",
    process: "下盖注塑",
    mode: "飞边/毛刺",
    effect: "外观不良",
    sev: 5,
    cause: "模具磨损",
    pc: "模具寿命管理",
    occ: 4,
    dc: "外观全检",
    det: 2,
    rpn: 40,
    ap: "L",
    action: "制定模具保养计划",
    resp: "模具工程部",
    date: "2026-05-25",
    status: "closed",
    sev2: 5,
    occ2: 2,
    det2: 2,
    rpn2: 20,
  },
  {
    id: "fmea-008",
    process: "螺柱结构",
    mode: "螺柱断裂",
    effect: "结构松动异响",
    sev: 7,
    cause: "扭矩过大",
    pc: "扭矩控制",
    occ: 3,
    dc: "扭矩监测",
    det: 3,
    rpn: 63,
    ap: "M",
    action: "电动螺丝刀扭矩校准",
    resp: "装配工程部",
    date: "2026-05-28",
    status: "closed",
    sev2: 7,
    occ2: 2,
    det2: 2,
    rpn2: 28,
  },
  {
    id: "fmea-009",
    process: "电池仓",
    mode: "接触不良",
    effect: "设备间歇断电",
    sev: 8,
    cause: "弹片弹力衰减",
    pc: "弹片寿命测试",
    occ: 3,
    dc: "接触电阻测量",
    det: 3,
    rpn: 72,
    ap: "M",
    action: "更换高弹性材料弹片",
    resp: "结构设计部",
    date: "2026-06-01",
    status: "closed",
    sev2: 8,
    occ2: 1,
    det2: 2,
    rpn2: 16,
  },
  {
    id: "fmea-010",
    process: "按键组装",
    mode: "按键卡死",
    effect: "用户无法操作",
    sev: 7,
    cause: "导光柱偏位",
    pc: "装配工装定位",
    occ: 2,
    dc: "按键力测试",
    det: 3,
    rpn: 42,
    ap: "L",
    action: "优化导光柱定位结构",
    resp: "结构设计部",
    date: "2026-06-05",
    status: "closed",
    sev2: 7,
    occ2: 1,
    det2: 2,
    rpn2: 14,
  },
  {
    id: "fmea-011",
    process: "线束连接",
    mode: "端子退针",
    effect: "信号中断",
    sev: 8,
    cause: "压接力不足",
    pc: "压接参数监控",
    occ: 3,
    dc: "拉拔力测试",
    det: 3,
    rpn: 72,
    ap: "M",
    action: "增加压接力在线监测",
    resp: "装配工程部",
    date: "2026-06-08",
    status: "pending",
    sev2: 8,
    occ2: 1,
    det2: 2,
    rpn2: 16,
  },
  {
    id: "fmea-012",
    process: "外壳喷涂",
    mode: "附着力不良",
    effect: "掉漆/外观缺陷",
    sev: 5,
    cause: "底材处理不足",
    pc: "等离子处理参数",
    occ: 3,
    dc: "百格测试",
    det: 2,
    rpn: 30,
    ap: "L",
    action: "增加等离子处理时间",
    resp: "涂装工程部",
    date: "2026-06-10",
    status: "closed",
    sev2: 5,
    occ2: 1,
    det2: 2,
    rpn2: 10,
  },
  {
    id: "fmea-013",
    process: "防水测试",
    mode: "泄漏",
    effect: "IP等级降级",
    sev: 9,
    cause: "密封胶涂覆不均",
    pc: "胶量监控",
    occ: 2,
    dc: "水浸测试",
    det: 2,
    rpn: 36,
    ap: "L",
    action: "自动点胶设备升级",
    resp: "工艺工程部",
    date: "2026-06-12",
    status: "closed",
    sev2: 9,
    occ2: 1,
    det2: 1,
    rpn2: 9,
  },
  {
    id: "fmea-014",
    process: "老化测试",
    mode: "误判合格",
    effect: "早期失效流出",
    sev: 8,
    cause: "老化时间不足",
    pc: "老化程序验证",
    occ: 2,
    dc: "出货前全检",
    det: 4,
    rpn: 64,
    ap: "M",
    action: "延长老化周期至48h",
    resp: "测试工程部",
    date: "2026-06-15",
    status: "pending",
    sev2: 8,
    occ2: 1,
    det2: 3,
    rpn2: 24,
  },
  {
    id: "fmea-015",
    process: "包装入库",
    mode: "标签贴错",
    effect: "发货错误",
    sev: 6,
    cause: "人工贴标差错",
    pc: "条码扫描核对",
    occ: 3,
    dc: "出库复核",
    det: 2,
    rpn: 36,
    ap: "L",
    action: "导入自动贴标系统",
    resp: "仓储物流部",
    date: "2026-06-18",
    status: "closed",
    sev2: 6,
    occ2: 1,
    det2: 2,
    rpn2: 12,
  },
  {
    id: "fmea-016",
    process: "FPC焊接",
    mode: "焊盘剥离",
    effect: "信号断路",
    sev: 8,
    cause: "烙铁温度过高",
    pc: "温度曲线监控",
    occ: 3,
    dc: "微切片检查",
    det: 4,
    rpn: 96,
    ap: "M",
    action: "导入脉冲热压焊",
    resp: "焊接工程部",
    date: "2026-06-20",
    status: "closed",
    sev2: 8,
    occ2: 1,
    det2: 3,
    rpn2: 24,
  },
  {
    id: "fmea-017",
    process: "屏幕贴合",
    mode: "气泡/异物",
    effect: "显示不良",
    sev: 6,
    cause: "洁净度不足",
    pc: "千级洁净室管控",
    occ: 3,
    dc: "AOI外观检测",
    det: 2,
    rpn: 36,
    ap: "L",
    action: "增加离子风枪除尘",
    resp: "贴合工程部",
    date: "2026-06-22",
    status: "closed",
    sev2: 6,
    occ2: 1,
    det2: 2,
    rpn2: 12,
  },
  {
    id: "fmea-018",
    process: "散热设计",
    mode: "热阻过高",
    effect: "芯片降频/死机",
    sev: 9,
    cause: "导热硅脂涂覆不均",
    pc: "涂覆量监控",
    occ: 3,
    dc: "热成像检测",
    det: 3,
    rpn: 81,
    ap: "M",
    action: "导入自动点胶涂覆",
    resp: "热设计部",
    date: "2026-06-25",
    status: "pending",
    sev2: 9,
    occ2: 1,
    det2: 2,
    rpn2: 18,
  },
  {
    id: "fmea-019",
    process: "天线装配",
    mode: "辐射效率低",
    effect: "通信距离缩短",
    sev: 7,
    cause: "天线间距不当",
    pc: "仿真验证",
    occ: 2,
    dc: "暗室测试",
    det: 3,
    rpn: 42,
    ap: "L",
    action: "优化天线布局间距",
    resp: "射频工程部",
    date: "2026-06-28",
    status: "closed",
    sev2: 7,
    occ2: 1,
    det2: 2,
    rpn2: 14,
  },
  {
    id: "fmea-020",
    process: "ESD防护",
    mode: "静电击穿",
    effect: "IC损坏",
    sev: 9,
    cause: "TVS管选型不当",
    pc: "ESD仿真分析",
    occ: 2,
    dc: "ESD枪测试",
    det: 3,
    rpn: 54,
    ap: "M",
    action: "升级TVS管规格",
    resp: "硬件工程部",
    date: "2026-07-01",
    status: "pending",
    sev2: 9,
    occ2: 1,
    det2: 2,
    rpn2: 18,
  },
]

/* ── BOM Tree Node to Process Mapping ── */
export const bomProcessMapping: Record<string, string[]> = {
  "asm-001": [], // All (root level shows everything)
  "sub-001": ["上盖注塑", "卡扣结构", "密封圈装配"],
  "sub-002": ["SMT贴片", "波峰焊", "功能测试", "FPC焊接"],
  "sub-003": ["下盖注塑", "螺柱结构"],
  "prt-001": ["上盖注塑"],
  "prt-002": ["卡扣结构"],
  "prt-003": ["密封圈装配"],
  "prt-004": ["SMT贴片"],
  "prt-005": ["波峰焊"],
  "prt-006": ["功能测试"],
  "prt-007": ["下盖注塑"],
  "prt-008": ["螺柱结构"],
}
