// Auto-generated by scripts/bump-app-version.mjs. Do not edit by hand.
export const APP_DISPLAY_NAME = "Logitech_V12.0.1";
export const APP_VERSION = "V12.0.1";
export const APP_TITLE = "Logitech_V12.0.1";
